Add check_output() for python 2.6 or earlier.
subprocess.check_output() was introduced in python 2.7.
In python 2.6 environment like RHEL/CentOS 6.x, execution of mesos-docker fails with this error:

```
AttributeError: 'module' object has no attribute 'check_output'
```

This patch adds check_output() for python 2.6 or earlier.